---
- name: Testing tags
  hosts: ansible-node3-rhel86
  become: yes
  tasks:
    - name: Display the hostname 
      command: "{{command_1}}"
      register: task1
      tags: [never, tsk1]

    - name: debug
      debug:
        var: task1 
        # msg: "{{task1.stdout}}"
      when: task1 is success


    - name: Display the kernal
      command: "{{command_2}}"
      register: task2
      tags: [never, tsk2]

    - name: Print message
      debug:
        msg: "{{task2.stdout}}"
      when:  task2 is success

