- name: Clearing the deviation for the given files
  hosts: all
  ignore_errors: yes
  tasks:
    - name: Analyzing the permission before the change
      shell:
          "hostname; ls -ld {{item.1}}"
      register: permission_before
      delegate_to: "{{item.0.srv1}}"
      with_subelements:
        - "{{server_name}}"
        - dirpath

    - name: Clearing the deviation
      shell:
        " ls -ld {item.1}}"
      delegate_to: "{{item.0.srv1}}"
      with_subelements:
        - "{{server_name}}"
        - dirpath

    - name: Analyzing the permission after the change
      shell:
        "hostname ; ls -ld {{item.1}}"
      register: permission_after
      delegate_to: "{{item.0.srv1}}"
      with_subelements:
        - "{{server_name}}"
        - dirpath

    - name: Result - The permission before the change
      debug:
              # msg: "{{permission_before | json_query('results[*].stdout.split('\n')')}}"
        msg: "{{permission_before.results|map(attribute='stdout_lines')| flatten|unique }}"  ### GOOD AS EXPECTED
        # "{{permission_after.results|map(attribute='stdout')|join('|')}}
        # delegate_to: "{{item.0.srv1}}"
        # with_subelements:
        # - "{{server_name}}"
        # - dirpath
              # msg: "{{permission_after | json_query('results[*].stdout')}}"
    - name: Result - The permission after the changee
      debug:
        msg: "{{permission_after.results|map(attribute='stdout_lines')|flatten|unique }}"
              # msg: "{{permission_after | json_query('results[*].stdout')}}"

