---
- name: Creating multiple users with password
  hosts: rhel69
  become: yes
  vars_files: 
    - vars.yaml
  tasks:
    - name: Creating users
      user:
        name: "{{item.name}}"
        password: "{{item.password}}"
        state: present
      loop: "{{users}}"
    - name: Clearing the fail logs in RHEL VMs
      shell: faillock --user {{item.name}} --reset
      when: ansible_os_family == "RedHat"
      loop: "{{users}}"
    - name: Clear the fail logs in AIX VMs
      shell: faillock --user {{item.name}} --reset ## Give exact command for AIX ##
      when: ansible_os_family == "AIX"
      loop: "{{users}}" 

