---
- name: User password reset
  #hosts: ansible-node2-rhel76,ansible-node4-ubuntu20,ansible-node3-rhel86
  hosts: ansible-node3-rhel86
  become: yes
  vars:
    secret: 
  tasks:
    - name: Get all users
      getent:
        database: passwd
        split: ':'
        # - name: debug the users
        # debug:
        # var: getent_passwd
        # - name: Print the usernames
        # debug:
        #  msg: "{{ getent_passwd | dict2items | map(attribute='key') | list }}"
    - name: Check if a root user exists
      debug:
        msg: The user iusr_sppagent  exists
      when: ( "iusr_sppagent" in getent_passwd.keys() )
      register: status1
    - name: Check of iusr_spporacle user 
      debug: 
        msg: The user iusr_spporacle exists
      when: ( "iusr_spporacle" in getent_passwd.keys() )
      register: status2


    - name: Print the status register
      debug:
        var: status2
        #    - name: Printing the messge
        # debug:
        # msg: Good
        # when: "{{status.failed == false }}"
        # ignore_errors: yes

    - name: reset password for user iusr_sppagent
      user:
        name: iusr_sppagent
        update_password: always
        #password: "{{ 'mypass'|password_hash('sha512')}}"
        password: $6$iLtctv8nipdHFJux$.2I773C7pjmggWmwS5daq3SfiTGdsjAxuE7rUI57ouPtM88xlvpqtktcwy4cBe3qHr3saomipho8f41LqMxLK. 
      when: ansible_distribution == "RedHat"

    - name: reset password for user iusr_spporacle
      user:
        name: iusr_spporacle
        update_password: always
        password: "{{ 'mypass'|password_hash('sha512')}}"
      when: ansible_distribution == "RedHat" and status2.failed == false
        #when: "{{status.failed == false }}"




