---
- name: Password change for all windows servers
  hosts: all
  become: false
  vars:
    win_pass: Redhatroot123@
  tasks:
    - name: Reset password for windows servers
      win_user: 
        name: normaluser1
        password: "{{win_pass}}"
        state: present
