---
- name: Create user on a linux server
  hosts: ansible-node1
  become: yes
  gather_facts: false
  vars_files:
    - vars.yaml
  tasks:
    - name: Create a login user
      user:
        name: "{{ item.name }}"
        #   password: "{{ item.password }}"
      	state: present
      with_items: "{{users}}" 

      #    - name: Clear the failed logs
      # shell:  faillock --user {{item.name}} --reset
      # when: ansible_os_family == "RedHat"
      # loop: "{{users}}"

...
