---
- name: some
  hosts: all
  vars:
    uname: 
      - xray
      - yray
  tasks:
    - name: set fact
      set_fact:
        generated_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits,hexdigits,@,#,$,%,^,*,') }}"
                
    - name: Create password
      user:
        name: "{{item}}"
        update_password: always
        password: "{{ generated_password | password_hash('sha512') }}"
        #update_password: always
      loop: "{{uname}}"
      when: ansible_facts['os_family'] == 'RedHat'
      
    - name: Changing the password for user in AIX Servers
      shell: echo ibmsasc:{{ generated_password }} | chpasswd; pwdadm -c ibmsasc
      when: ansible_facts['os_family'] == "AIX"
      
    - name: Changing the password for user in AIX Servers
      shell: echo ibmsase:{{ generated_password }} | chpasswd; pwdadm -c ibmsase
      when: ansible_facts['os_family'] == "AIX"
      
    - name: Create the csv file
      lineinfile:
        path: /tmp/pass.csv
        create: yes
        line: "{{uname}},{{generated_password}}"
