---
- name: Create user and random password
  hosts: all
  vars:
    uname: xray
        #    password: "{{ lookup('password', 'credentials/' + uname + ' length=9') }}"

  tasks:
    - name: set fact
      set_fact:
        generated_password: "{{ lookup('password', 'credentials/' + uname + ' length=16') }}"
        until: generated_password | search('[0-9]') and generated_password | search('[A-Za-z]') and generated_password | search('[.,:-_]')
      with_sequence: count=2
      retries: 1
      delay: 3

    - name: Create password
      #  vars:
      #  password: "{{ lookup('password', 'credentials/' + item + ' length=9') }}"
      user:
        name: "{{item}}"
        update_password: always
        password: "{{ generated_password | password_hash('sha512') }}"
        #update_password: always
      loop:
       - "{{uname}}"
    - name: Create the csv file
      lineinfile:
        path: /tmp/passss.csv
        create: yes
        line: "{{uname}},{{generated_password}}"
