---
- hosts: ansible-node2-rhel76
  become: yes
  tasks:
  - name: find the nmon files
    find:
      paths: "/bustools/nmon/data/"
      recurse: no
      patterns: "*.nmon"
    register: nmon_files
  
  - name: print files
    ansible.builtin.debug:
      var: nmon_files

  - name: find the nmon csv files 
    ansible.builtin.find:
      paths: "/bustools/nmon/csv/"
      hidden: true
      recurse: true
      file_type: any
      patterns: "*.gz"
    register: csv_files


  - name: print files
    ansible.builtin.debug:
      var: csv_files

      #  - name: Fetch the nmon files
      # fetch:
      # src: "{{ item.path }}"
      # dest: "/tmp/"
      # flat: yes
      # with_items: "{{ nmon_files.files }}"
      # register: nmon_status
  - name: Create a dir in tower
    file:
      path: /tmp/nmon/{{ansible_hostname}}
      state: directory
      #delegate_to: localhost
      mode: '0755'
    delegate_to: localhost

  - name: Fetch the csv files
    fetch:
      src: "{{ item.path }}"
      # dest: "/tmp/"
      dest: /tmp/nmon/{{ansible_hostname}}
      flat: yes
    with_items: "{{ csv_files.files }}"
    register: csv_status

  - debug:
      var: nmon_status
  - debug:
      var: csv_status

      # - name: Copy the file from tower to nmon server
      # copy:
      # src: "{{ item.dest }}"
      # dest: /busdata/rsm/eur0/_lgi/nmon/data/{{ansible_hostname}}/chart/
      # delegate_to: ansible-node3-rhel86
      # register: status
      # with_items: "{{nmon_status.results}}"

  - name: Copy the csv file from tower to nmon server
    copy:
            #src: "{{ item.dest }}"
      src: /tmp/nmon/
      dest: /busdata/rsm/eur0/_lgi/nmon/data/{{ansible_hostname}}/chart/
    delegate_to: ansible-node3-rhel86
    register: status2
    #with_items: "{{csv_status.results}}"

  - name: Debug the status
    debug:
      var: status2
  - name: collect the current files
    find:
      paths: "/busdata/rsm/eur0/_lgi/nmon/data/{{ansible_hostname}}/chart/"
      hidden: true
      recurse: true
      file_type: any
      patterns: "*.csv"
    register: collected_files
    delegate_to: ansible-node3-rhel86

  - name: debug
    debug:
      var: collected_files

  - name: remove the collected files
    file:
      path: "{{item.path}}"
      state: absent
    with_items: "{{collected_files.files}}"
    delegate_to: ansible-node3-rhel86
  - name: Unzip the files
    shell:
      cmd:  gunzip {{item.dest}}
    with_items: "{{status2.results}}"
    register: final
    delegate_to: ansible-node3-rhel86
    become: yes

  - name: collect the current files
    find:
      paths: "/busdata/rsm/eur0/_lgi/nmon/data/{{ansible_hostname}}/chart/"
      hidden: true
      recurse: true
      file_type: any
      patterns: "*.csv"
    register: collected_files2
    delegate_to: ansible-node3-rhel86

  - name: debug the converted csv files
    debug:
      var: collected_files2

  - name: applying fergal command
    shell:
      cmd: sort {{item.path}}|sed 's/,/\./g'|sed 's/;/,/g' > {{item.path}}.nmon
    delegate_to: ansible-node3-rhel86
    with_items: "{{collected_files2.files}}"
    become: yes

  - name: collect the current nmon files
    find:
      paths: "/busdata/rsm/eur0/_lgi/nmon/data/{{ansible_hostname}}/chart/"
      hidden: true
      recurse: true
      file_type: any
      patterns: "*.nmon"
    register: collected_files3
    delegate_to: ansible-node3-rhel86

  - name: debug the nmon file path
    debug:
      var: collected_files3

  - name: Finally convert the nmon files to html
    shell:
      cmd: /root/nmonchart/nmonchart {{item.path}} {{item.path}}.html
    delegate_to: ansible-node3-rhel86
    with_items: "{{collected_files3.files}}"
    become: yes 
  
  - name: Remove the dir from tower
    file:
      path: /tmp/nmon
      state: absent
    delegate_to: localhost

      # chdir: /busdata/rsm/eur0/_lgi/nmon/data/{{ansible_hostname}}/chart/
    #shell: gunzip {{item}} /busdata/rsm/eur0/_lgi/nmon/data/{{ansible_hostname}}/chart/
            # src: /busdata/rsm/eur0/_lgi/nmon/data/{{ansible_hostname}}/chart/*.gz
            
    # dest: /busdata/rsm/eur0/_lgi/nmon/data/{{ansible_hostname}}/chart/
    #remote_src: yes
    #  - name: convert the csv file to html with fergel command
    # shell: |
    #  for i in /busdata/rsm/eur0/_lgi/nmon/data/{{ansible_hostname}}/chart/ *.csv; do
    #    /bin/mv -iv "$i" "(basename "$i" .csv).nmon"
    #  done  




      # shell: sudo sort /busdata/rsm/eur0/_lgi/nmon/data/{{ansible_hostname}}/chart/*.csv /busdata/rsm/eur0/_lgi/nmon/data/{{ansible_hostname}}/chart/*.nmon
      # delegate_to: ansible-node3-rhel86
    #with_items: "{{status2.results.path }}"  
    # - name: Convert the nmon file to html
    # shell: /root/nmonchart/nmonchart  /busdata/rsm/eur0/_lgi/nmon/data/{{ansible_hostname}}/chart/*.nmon /busdata/rsm/eur0/_lgi/nmon/data/{{ansible_hostname}}/chart/*.html
    #shell: sudo /root/nmonchart/nmonchart  {{item.dest}} {{item.dest}}.html
    # with_items: "{{status.results}}"
    #delegate_to: ansible-node3-rhel86
 

    #  - name: Convert the nmon file to html
    # shell: /root/nmonchart/nmonchart  /busdata/rsm/eur0/_lgi/nmon/data/{{ansible_hostname}}/chart/{{item.path}} /busdata/rsm/eur0/_lgi/nmon/data/{{ansible_hostname}}/chart/{{item.path}}
    #   shell: sudo /root/nmonchart/nmonchart  {{item.dest}} {{item.dest}}.html
    #with_items: "{{status2.results}}"
    # delegate_to: ansible-node3-rhel86
    # - name: change the extensing to only html
    # shell: mv {{item.dest}}.html


